// obsidian-plugin/esbuild.config.mjs
// Bundles the Scholar Sidekick Obsidian plugin to main.js (CommonJS, the
// only module format Obsidian's plugin loader accepts).

import { context, build } from "esbuild";
import builtins from "builtin-modules";

const production = process.argv[2] === "production";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const options = {
  banner: { js: banner },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
  ],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: production ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  minify: production,
};

if (production) {
  await build(options);
  process.exit(0);
} else {
  const ctx = await context(options);
  await ctx.watch();
}
